version: '3'
services:
  app:
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    image: ${IMAGE:-knightniwrem/ddi}
    networks:
      - ddi-network
    volumes:
      - ./configs:/ddi/configs
      - ./src:/ddi/src
  db:
    image: 'postgres:13-alpine'
    env_file:
      - ./configs/.env
    networks:
      - ddi-network
    ports:
      - ${POSTGERS_PORT:-5432}:5432
    restart: always
    volumes:
      - ddi-db:/var/lib/postgresql/data
networks:
  ddi-network:
volumes:
  ddi-db:
